version: "3"
services:
    web:
        build: .
        ports:
            - "5003:80"
            - "5004:443"
        environment: 
            - "ASPNETCORE_ENVIRONMENT=Development"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:latest"
        environment:
            SA_PASSWORD: "EmanuelaPreslavaEmiliaTop2"
            ACCEPT_EULA: "Y"
    redis:
        image: "redis:latest"
            