version: '3.6'
services:
    db:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: mssqlserver
        environment:
            SA_PASSWORD: "EmanuelaPreslavaEmilia2"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433
        
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
            
    asp:
        container_name: besl-web
        build: .
        ports:
            - 5000:80
            - 5001:443
        environment:
            - ASPNETCORE_URLS=http://+:80;https://+:443
        depends_on:
            - db
            - redis