name: ci

on: [push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup .NET SDK 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Build
        run: ./build.sh --configuration Release

      - name: Run Unit Tests
        run: ./build.sh rununittests --configuration Debug

      - name: Upload Code Coverage Report as Artifact
        uses: actions/upload-artifact@v2.2.4
        with: 
          name: coverage-report
          path: ./artifacts/*_coverage.xml
      
      - name: Publish Code Coverage Report to CodeCov
        run: ./build.sh uploadcodecoverageartifact
        env:
          CodeCovToken: ${{ secrets.CodeCovToken }}
      
      - name: Publish Docker Image
        run: ./build.sh publishdockerimage --configuration Release
        env:
          GitHubPersonalAccessToken: ${{ secrets.GITHUB_TOKEN }}
          GitHubUsername: ${{ github.actor }}
