name: ci

on: [push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup .NET SDK 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Build
        run: ./build.sh --configuration Release

      - name: Run Unit Tests
        run: ./build.sh rununittests --configuration Debug
